export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SHOP_INFO = "GET_SHOP_INFO";
export const MORE_PRODUCTS = "MORE_PRODUCTS";

export const GET_TRENDING_PRODUCTS = "GET_TRENDING_PRODUCTS";
export const MORE_TRENDING_PRODUCTS = "MORE_TRENDING_PRODUCTS";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
